### ISSUE TITLE
第91行，95行没有参数传入

### ISSUE THREAD

**Issue by kingname** [2shou/QuickORM#2]
第91行，95行，cls.connect()这个地方并没有传入参数，所以在def connect(cls, **db_config)这个方法里面，db_config实际上得到的一直是一个空字典。但是由于你设定了默认参数，因此不会出错，但是如果别人的数据库不是这些默认的参数，就会出问题。

**Comment by 2shou** [comment]
修复了，年久失修，一时想不到很漂亮的代码，也许你可以有更美的方案。
